### ISSUE TITLE
Error downloading a specific version

### ISSUE THREAD

**Issue by olaxe** [bodaay/HuggingFaceModelDownloader#1]
Thanks for adding a specific version setting as discussed.
I have an issue with this:
./hfdownloader -m TheBloke/WizardLM-33B-V1.0-Uncensored-GGML:q4_K_M
Model: TheBloke/WizardLM-33B-V1.0-Uncensored-GGML:q4_K_M
Branch: main
DestinationPath: Storage
NumberOfConcurrentConnections: 5
Token: 

Filter Has been applied, will include LFS Model Files that contains: [q4_k_m]Error: unlinkat Storage/TheBloke_WizardLM-33B-V1.0-Uncensored-GGML/tmp: directory not empty
2023/06/25 05:56:44 Error: unlinkat Storage/TheBloke_WizardLM-33B-V1.0-Uncensored-GGML/tmp: directory not empty

I can rerun the download by removing the folder manually.

**Comment by bodaay** [comment]
`Model: TheBloke/WizardLM-33B-V1.0-Uncensored-GGML:q4_K_M
Branch: main
DestinationPath: Storage
NumberOfConcurrentConnections: 5
Token:

Filter Has been applied, will include LFS Model Files that contains: [q4_k_m]
Getting File Download Files List Tree from: https://huggingface.co/api/models/TheBloke/WizardLM-33B-V1.0-Uncensored-GGML/tree/main/
Checking Existsing file: Storage/TheBloke_WizardLM-33B-V1.0-Uncensored-GGML/.gitattributes
file size matched for non LFS file: Storage/TheBloke_WizardLM-33B-V1.0-Uncensored-GGML/.gitattributes
Checking Existsing file: Storage/TheBloke_WizardLM-33B-V1.0-Uncensored-GGML/README.md
file size matched for non LFS file: Storage/TheBloke_WizardLM-33B-V1.0-Uncensored-GGML/README.md
Skipping: Storage/TheBloke_WizardLM-33B-V1.0-Uncensored-GGML/.gitattributes
Skipping: Storage/TheBloke_WizardLM-33B-V1.0-Uncensored-GGML/README.md
Filter Skipping: Storage/TheBloke_WizardLM-33B-V1.0-Uncensored-GGML/wizardlm-33b-v1.0-uncensored.ggmlv3.q2_K.bin
Filter Skipping: Storage/TheBloke_WizardLM-33B-V1.0-Uncensored-GGML/wizardlm-33b-v1.0-uncensored.ggmlv3.q3_K_L.bin
Filter Skipping: Storage/TheBloke_WizardLM-33B-V1.0-Uncensored-GGML/wizardlm-33b-v1.0-uncensored.ggmlv3.q3_K_M.bin
Filter Skipping: Storage/TheBloke_WizardLM-33B-V1.0-Uncensored-GGML/wizardlm-33b-v1.0-uncensored.ggmlv3.q3_K_S.bin
Filter Skipping: Storage/TheBloke_WizardLM-33B-V1.0-Uncensored-GGML/wizardlm-33b-v1.0-uncensored.ggmlv3.q4_0.bin
Downloading Storage/TheBloke_WizardLM-33B-V1.0-Uncensored-GGML/wizardlm-33b-v1.0-uncensored.ggmlv3.q4_K_M.bin Speed: 12.80 MB/sec, 0.34% ^C`

I'm trying to reproduce the issue without success

you still facing it?
