### ISSUE TITLE
[feature] proxy need

### ISSUE THREAD

**Issue by xiaohangguo** [bodaay/HuggingFaceModelDownloader#14]
Is it possible to develop a proxy address feature, in my country, the direct download https://huggingface.co network is not connected, you need to use a proxy, this proxy method
`export HF_ENDPOINT=https://hf-mirror.com`

**Comment by bodaay** [comment]
pleae consider my answer in this issue if it will be sufficient in your case #11

**Comment by xiaohangguo** [comment]
> pleae consider my answer in this issue if it will be sufficient in your case #11


thanks
