### ISSUE TITLE
Cursor jittering in Tmux

### ISSUE THREAD

**Issue by zereraz** [bodaay/HuggingFaceModelDownloader#18]
Cursor constantly moving back and forth if I press enter even once during download.

https://github.com/bodaay/HuggingFaceModelDownloader/assets/2609361/94bba915-3c08-4d50-ad16-4ad2f728e995

<img width="1727" alt="image" src="https://github.com/bodaay/HuggingFaceModelDownloader/assets/2609361/3b6d4efb-5571-4c21-9702-6177443803cc">
also such repeated text at times

**Comment by bodaay** [comment]
actually i noticed this issue even is vscode terminal, sometime it crash vscode completely, I need to change the progress flow code

**Comment by bodaay** [comment]
as an alternate, not a complete fix, you can disable progress bar printing by using silentMode, it will print start and finished, but no progress

**Comment by issuj** [comment]
Cursor jittering is probably fixed by #36 which limits the redraw of status line to 10 times per seconds (was unlimited).

**Comment by bodaay** [comment]
Thanks for the reminder
