### ISSUE TITLE
Specific model TheBloke/WizardLM-Uncensored-Falcon-7B-GGML:q4_k_m doesn't use a specific folder

### ISSUE THREAD

**Issue by olaxe** [bodaay/HuggingFaceModelDownloader#2]
It will be nice to have a specific folder name when a specific model file is requested through filtering.
 -m TheBloke/WizardLM-33B-V1.0-Uncensored-GGML:q4_K_M

Will create this specific folder TheBloke_WizardLM-33B-V1.0-Uncensored-GGML-q4_K_M
and not TheBloke_WizardLM-33B-V1.0-Uncensored-GGML

So it is easier to select it in the text-generation-webui.

**Comment by bodaay** [comment]
Sure this can easily be done, but what about when you select multiple filters? What about the other files inlcuded with the model?

**Comment by bodaay** [comment]
ok found a nice solution to this
I see the value of your request and really appreciate this awesome idea, I'm done with implementing it, just testing out now all scenarios

**Comment by bodaay** [comment]
its ready, test it out in release 1.1.7
you can use it by adding flag: -f

or directly run latest:
`bash <(curl -sSL https://g.bodaay.io/hfd) -f -m TheBloke/vicuna-13b-v1.3.0-GGML:q4_0,q5_0`
