### ISSUE TITLE
Feature Request: Silent mode

### ISSUE THREAD

**Issue by nylocx** [bodaay/HuggingFaceModelDownloader#22]
I'm using hfdownloader in a docker container and I really would like to have to option to slience the progress to only have one "line" per file. Otherwise you will quickly see something like "buildx output clipped 200KiB/s reached" as every update to the progress bar is written to the build log.

something like `--progress=[interactive,static,disabled]` might be good with static only giving an output once a download starts and once it finishes.

**Comment by bodaay** [comment]
This has been implemented with version 1.3.4, you can use -q flag
it will only disable progress bar printing, but will print "starting and finished"
