### ISSUE TITLE
download stops

### ISSUE THREAD

**Issue by EdwardDali** [bodaay/HuggingFaceModelDownloader#3]
I'm using an external hard drive (not sure if it's related to the issue) but the download stops at merging chunks and verifying hashes. It's starting again by pressing enter (but not from the first enter)

**Comment by bodaay** [comment]
is this on windows?

**Comment by EdwardDali** [comment]
Yes. Seems to work fine with smaller files so I think it's actually not an issue. It only occurs with some 9Gb files.

**Comment by bodaay** [comment]
this is I think the famous issue with windows console
for some reason it put running process into sleep until you click something on keyboard while the window active

you can fix this forever and for any application, by turning off "QuickEdit" Mode from the preferences menu

you can read about it here:
https://superuser.com/questions/312132/command-prompt-hangs-until-keypress

**Comment by EdwardDali** [comment]
That's great news! Thank you!
