### ISSUE TITLE
Filter downloads multiple files and not just a single one

### ISSUE THREAD

**Issue by haznai** [bodaay/HuggingFaceModelDownloader#31]
**[huggingface model repo](https://huggingface.co/Mozilla/Meta-Llama-2-8B-Instruct-llamafile/tree/main)**

I may have misunderstood something, but I expected the following command to download just a single file, namely: 

<img width="1266" alt="Screenshot 2024-05-29 at 16 36 36" src="https://github.com/bodaay/HuggingFaceModelDownloader/assets/43835582/0af3dec6-aa5f-4ce3-befb-f02cd40361ff">

```
./hfdownloader  -m "Mozilla/Meta-Llama-3-8B-Instruct-llamafile:Q8_0" -t hf_xxx
```

Instead of a single file, the `hfdownloader` starts with the first file in the repo (a file that doesn't contain the `q8_0`):

```
Filter Has been applied, will include LFS Model Files that contains: [q8_0]
Getting File Download Files List Tree from: https://huggingface.co/api/models/Mozilla/Meta-Llama-3-8B-Instruct-llamafile/tree/main/
Checking file size matching: downloads/Mozilla_Meta-Llama-3-8B-Instruct-llamafile/.gitattributes
Checking file size matching: downloads/Mozilla_Meta-Llama-3-8B-Instruct-llamafile/LICENSE.llamafile

Downloading downloads/Mozilla_Meta-Llama-3-8B-Instruct-llamafile/Meta-Llama-3-8B-Instruct.BF16.llamafile Speed: 2.39 MB/sec, 0.17%
```

mac info: 
<img width="392" alt="Screenshot 2024-05-29 at 16 40 13" src="https://github.com/bodaay/HuggingFaceModelDownloader/assets/43835582/206e6028-6256-4f74-85e8-c99e3b68a106">

**Comment by bodaay** [comment]
I'll implement that after I rework the code, the code base is missed up, I need to rework all commands and options

**Comment by bodaay** [comment]
llamafile extension was not supported, added this support in 1.4.0
