### ISSUE TITLE
Filtering and Downloading Models inside a folder

### ISSUE THREAD

**Issue by Yogesh-S-09** [bodaay/HuggingFaceModelDownloader#35]
I am trying to download `hfdownloader -j bartowski/DeepSeek-V2.5-GGUF:Q4_0` but it's downloading all the files inside each folders files.

**Comment by Kaszebe** [comment]
Did you figure it out?

**Comment by bodaay** [comment]
this is fixed in 1.3.9

filters should work properly when the model within a subfolder
