### ISSUE TITLE
linux x86 binary fails on WSL

### ISSUE THREAD

**Issue by the-crypt-keeper** [bodaay/HuggingFaceModelDownloader#4]
Using WSL `Linux DESKTOP-MH2FEL7 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

I get:

```
$ bash <(curl -sSL https://g.bodaay.io/hfd)
Download successful
./hfdownloader: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./hfdownloader)
./hfdownloader: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./hfdownloader)
```

WSL uses GLIBC 2.31 which I guess is too old to be supported by this binary.

**Comment by the-crypt-keeper** [comment]
on arm64 `Linux ubuntu-32gb-fsn1-1 5.15.0-72-generic #79-Ubuntu SMP Tue Apr 18 16:53:43 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux`, the install script fails:

```
root@ubuntu-32gb-fsn1-1:~# bash <(curl -sSL https://g.bodaay.io/hfd) -h
curl: (22) The requested URL returned error: 404
Download failed
chmod: cannot access 'hfdownloader': No such file or directory
/dev/fd/63: line 34: ./hfdownloader: No such file or directory
```

**Comment by bodaay** [comment]
all the testing I've done on WSL, running ubuntu 22.04
Ubuntu 22.04.2 LTS (GNU/Linux 5.10.16.3-microsoft-standard-WSL2 x86_64)

I think this is running an old version of linux, this is same issue when I try to run compiled go code from ubuntu 22, on ubuntu 18

as for the arm part, I think this is default config I used for building on raspberry pi :)

**Comment by xiaohangguo** [comment]
> all the testing I've done on WSL, running ubuntu 22.04 Ubuntu 22.04.2 LTS (GNU/Linux 5.10.16.3-microsoft-standard-WSL2 x86_64)
> 
> I think this is running an old version of linux, this is same issue when I try to run compiled go code from ubuntu 22, on ubuntu 18
> 
> as for the arm part, I think this is default config I used for building on raspberry pi :)
I using docker solved this issue.
