### ISSUE TITLE
Hello everyone, I'm having trouble running AMD64 binaries. GLIBC

### ISSUE THREAD

**Issue by faelp22** [bodaay/HuggingFaceModelDownloader#40]
I downloaded this version: hfdownloader_linux_amd64_1.4.1

when running I got the following error: 

$ hfdownloader -m intfloat/e5-small-v2
hfdownloader: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by hfdownloader)
hfdownloader: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by hfdownloader)

$ sudo apt install libc6
Reading package lists... Done
Building dependency tree
Reading state information... Done
libc6 is already the newest version (2.31-0ubuntu9.16).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

I think I already have glibc6 installed and it still failed.

these are my server settings:

$ uname -a
Linux my-vm 5.4.0-198-generic #218-Ubuntu SMP Fri Sep 27 20:18:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

thank you for your attention

**Comment by bodaay** [comment]
this was issue due to that latest release which was built on Ubuntu 24.04 and had cgo_enabled=1
please delete the old binary and download 1.4.2
