### ISSUE TITLE
Resuming aborted download does not work

### ISSUE THREAD

**Issue by rrva** [bodaay/HuggingFaceModelDownloader#5]
1. Start downloading a large model
2. Break your internet connection
3. Resume internet connection (maybe with a different source ip)

Expected result: Resumes download at previous position
Actual: Timeout (and the timeout takes very long)

Error downloading chunk 3: read tcp 192.168.68.145:56343->108.157.214.31:443: read: can't assign requested address

1. Start downloading a large model
2. Abort the program (Ctrl+C)
3. Restart the download for the same model

Expected result: Resumes download at previous position
Actual result: Seems to restart download from scratch

**Comment by bodaay** [comment]
ok it will skip full downloaded files, but failed files with not resume

so if the model has 5 big files, 3 downloaded, 4th failed, it will re-download that particular failed file

while this can be implemented, I need to redesign how I'm dividing the chunks

now the chunks are divided based on number of connections, lets say you re-ran the utility but changed number of connection, whole thing will get messed up

I'll think about it, and see if it can be implemented in a better way, for now I'll just put this as enhancement not bug

**Comment by rrva** [comment]
Agree, its just a handy enhancement not a bug. In my case it was only a single large file:

```
hfdownloader -m TheBloke/WizardCoder-15B-1.0-GGML:q8_0
```

`wget -c` has this behavior when resuming normal http download. Uses the HTTP `Range` header.

**Comment by bodaay** [comment]
this is completed and implemented
commit ffde5b5

release 1.2.5

**Comment by rrva** [comment]
thanks!
