### ISSUE TITLE
Unable to use filter. windows build.

### ISSUE THREAD

**Issue by zoigo** [bodaay/HuggingFaceModelDownloader#8]
as said in title, i am unable to use the filter option,
tool proceeds to download all models from the smallest ones.

`.\hfdownloader_windows_amd64_1.2.7.exe -m TheBloke/CodeLlama-34B-Python-GGUF:Q6_K`
`Model: TheBloke/CodeLlama-34B-Python-GGUF:Q6_K`
`Filter Has been applied, will include LFS Model Files that contains: [q6_k]`
`Downloading CodeLLama2-Python/TheBloke_CodeLlama-34B-Python-GGUF/codellama-34b-python.Q2_K.gguf Speed: 28.44 MB/sec, 100.00%`
`Hash Matched for LFS file: CodeLLama2-Python/TheBloke_CodeLlama-34B-Python-GGUF/codellama-34b-python.Q2_K.gguf`
`Downloading CodeLLama2-Python/TheBloke_CodeLlama-34B-Python-GGUF/codellama-34b-python.Q3_K_L.gguf Speed: 28.31 MB/sec, 26.60%`

i was so happy finding this tool from author's answer on StackOverflow
thanks a lot!

**Comment by bodaay** [comment]
i can see the issue within this new extension gguf
the filter will only appies for known extension, 
i will release new version to support this extension
